name: Node.js CI

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    env:
      GOROD_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: restore cache
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: install packages
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

  code-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    needs: bootstrap

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: restore cache
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: install packages
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          GOROD_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: run check-types
        if: always()
        run: yarn check-types

      - name: run eslint
        if: always()
        run: yarn lint

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    needs: bootstrap

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: restore cache
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: install packages
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          GOROD_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: run tests
        if: always()
        run: yarn test
